### ISSUE TITLE
Example for storing level1 and level2 data

### ISSUE THREAD

**Issue by denisvolokh** [manahl/arctic#108]
Hi, 

Could you please make an example for storing level1 and level2 data using tick store?

**Comment by bmoscon** [comment]
what do you mean by level1 and level2 data?

**Comment by denisvolokh** [comment]
Level 1: bid, bid_size, ask, ask_size, volume
Level 2: order book updates

**Comment by bmoscon** [comment]
its really up to you how you'd organize your data. Do you want to store the data together, or in separate 'symbols' in the database? Easiest way would be to store in separate symbols, and write a dict to the tickstore, something like:

```
L1 = {'date': date, 'bid': bid, 'bid_size': bid_size, 'ask': ask, 'ask_size': ask_size}
L2 = {'order_book': ob}

tickstore_lib.write('L1_data', L1)
tickstore_lib.write('L2_data', L2)

```

Is that what you are asking? Also looping in @jamesblackburn since I have very limited experience using tickstore.

**Comment by bmoscon** [comment]
@denisvolokh does this answer your question?

**Comment by bmoscon** [comment]
also see the comments on #205. I give some example code there, though this uses dataframes, not dictionaries. You could store the L1 and L2 data in the same DF/Dict, or you could store L1 and L2 as separate symbols. @denisvolokh

**Comment by xgdgsc** [comment]
Can I get tick data by date range?

**Comment by bmoscon** [comment]
yes, there is a date range parameter to read: 

https://github.com/manahl/arctic/blob/master/arctic/tickstore/tickstore.py#L240


You can also see an example here:

https://github.com/manahl/arctic/blob/master/tests/integration/tickstore/test_ts_read.py#L197
