### ISSUE TITLE
Libraries use cases

### ISSUE THREAD

**Issue by felipe-ducau7c** [manahl/arctic#197]
Hi, 

I am working with historical minute data and was wondering which is the right library to store it. 

Most of the columns are numerical but I have some metadata on each transaction as well, some of which that I could encode as numerical just adding more columns (dummy variables), and some that are just strings adding information on the transaction. 

First thing I thought was to use TickStoreV3, but I'm struggling a bit with the metadata. 

Also, in a more general way, for which kind of data are the different libraries optimized for? 

Thanks!

**Comment by bmoscon** [comment]
Tickstore is for tick data. It is great for writing updates constantly. Data must be datetime indexed. I also believe it only supports read and write. 

VersionStore is for general use. It supports versioning, reading, writing and appending. It will write pretty much anything that is a dataframe/series or is pickleable.  

ChunkStore supports DataFrames/Series and is customizable in terms of chunk sizes and what the chunking paradigm is. Currently it chunks on dates, so the dataframe has to have an index or column that is named 'date' and has timestamps/datetimes in it. It could  easily be extended to something different. Its more useful for very large datasets that are chunked into Daily/Monthly/Yearly data.

If you are having issues with Tickstore, try out Version Store, as it allows you to store metadata with each symbol/dataframe.

**Comment by jamesblackburn** [comment]
And version store write supports passing a metadata dictionary.  

For storing minute data, it should work well.

**Comment by fducau** [comment]
Thank you @bmoscon and @jamesblackburn for your replies. 

So the choice between VersionStore and ChunkStore depends on the size of the data and if needs versioning or not, right?

Which would be your choice for historical  (3 years +) time indexed transaction data with daily updates? 

The idea here is to run Machine Learning algorithms on top of it. Which would be other things to keep in mind in order to make this decision?

Also feel free to contact me in case you need help witih the documentation. I am currently thinking about creating a couple of documents/posts or similar summarizing my first steps with Arctic.

**Comment by bmoscon** [comment]
@fducau it depends. If you want to be able to access data in that dataset very quickly by date (i.e. read out all the data for date 2015-7-8) I think ChunkStore is better. VersionStore allows you to read data by date, but the data isnt stored by date, so there can be some overhead reading back a specific date. If you need to write daily data more than a few times a day, I'd recommend against ChunkStore. This is because the chunks for a given date are stored together, so if you write data for a date many many times, there is some overhead. Example. If you write data for 2016-8-19 once, as in end of day, no problem. If you write data to the 2016-8-19 chunk every 10 seconds, ChunkStore will be slower than VersionStore. 

You can check out this issue: #192 . Another user did some comparison between ChunkStore and TickStore. His use case involves writing tickdata, a case for which ChunkStore is ill suited. From your description I think either one will work fine. You might want to do some tests. Write the historical data (say for a few years) and play with reading back the date ranges that seem reasonable. ChunkStore should do really well at this. I think VersionStore will be slower, but probably not a whole lot (I honestly do not know for sure though).

**Comment by bmoscon** [comment]
Also, I am currently working on the documentation. Once I have something ready, feel free to go over it and add in anything you think will help other users!

**Comment by fducau** [comment]
@bmoscon thanks a lot for the insight, I'll definetely run some tests in order to determine which one to go with. 

Maybe one approach to my particular needs would be to store daily data in VersionStore for incremental writes and intraday reads and do a daily dump to a ChunkStore for hystorical purposes. 

Please feel free to close the issue and thanks again for the support!

**Comment by bmoscon** [comment]
@fducau np. Feel free to email or open a new ticket if more questions arise.

**Comment by jamesblackburn** [comment]
@bmoscon not sure what you mean by 'data isn't stored by date' - it is date-ordered, and I believe we're doing the sensible thing in read to read the minimum number of chunks necessary :)
https://github.com/manahl/arctic/blob/master/arctic/store/_ndarray_store.py#L169

>Maybe one approach to my particular needs would be to store daily data in VersionStore for incremental writes and intraday reads and do a daily dump to a ChunkStore for hystorical purposes.

It's worth saying that we use VersionStore for minute bar data which has ~4M rows going back 20-30 years, and it works fine.  We also use VersionStore `append` for appending minute-by-minute as the data comes in.

Chunkstore does have some neat features - and I hope at some point these thing will be merged as data versioning has been very useful for us.
