### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by femtotrader** [manahl/arctic#200]
Hello,

it will be nice to provide Docker container to easily install arctic.

Kind regards

**Comment by mckelvin** [comment]
I guess it's irrelevant. Arctic is a library. If you find it's damn slow to build and install arctic, you should advise them to release a python wheel (every is built already as a binary package). Since there's no wheel package officially. I'm using devpi to build and release in-house wheel package for arctic.

**Comment by bmoscon** [comment]
PyPI won't let you upload Linux Wheels due to the various differences between distros. You can only upload Windows, OSX, or Universal Wheels.

**Comment by bmoscon** [comment]
I can create a "manylinux" wheel and upload that (similar to what Pandas does). I'll have to do it at home though, so it will take me a day or two to get around to this. I'll upload a 2.7 and 3.5 Linux wheel. That good enough, or is anyone using 3.4?

**Comment by mckelvin** [comment]
That's great! There're [pandas wheels](https://pypi.python.org/pypi/pandas) of version `2.7`, `3.4`, `3.5`. And these 3 versions are also listed in [.travis.yml](https://github.com/manahl/arctic/blob/master/.travis.yml#L4-L6) of Arctic. I guess maybe it's better to include `3.4`.

**Comment by bmoscon** [comment]
I uploaded a 2.7 and 3.5 wheel. I tested the 2.7 wheel, and it works for me on Ubuntu 16.04.


Unless there is any other issue with this, I'm going to close this ticket. (so speak now)

**Comment by femtotrader** [comment]
I don't use Python 3.4 so 2.7 and 3.5 wheels are enough

So no Docker container?
Docker container could provide an easy install of both MongoDB and Arctic.

**Comment by femtotrader** [comment]
This is the place where InfluxData provides its InfluxDB container
https://hub.docker.com/r/tutum/influxdb/

**Comment by bmoscon** [comment]
i just dont see what it buys anyone. If you want to run something in docker, most people are more likely to select the default image they want (centOS, Ubuntu, etc) and then install the version of mongo they want. Installing Mongo and installing arctic are just two short/brief steps in someone's dockerfile. 

what do you think @jamesblackburn and @TomTaylorLondon ?

**Comment by davidwneary** [comment]
Hi,

Just came across this as I found `pip install arctic` always takes a long time. The wheel is lightening fast by comparison but doesn't seem to be available for the latest version. Are there any plans to upload these for a newer version?

Cheers
Dave

**Comment by bmoscon** [comment]
I dont specifically know what error you are hitting, but I'm pretty sure if you preinstall some of the dependencies it will go significantly faster. Cython, numpy, pandas and pymongo if installed by the setup script tend to take a long time, for a strange reason 

also see: https://github.com/manahl/arctic/issues/9


I can build a wheel, but because of the compiler shared library its platform specific. Are you on linux or mac?

**Comment by bmoscon** [comment]
I've uploaded wheels for 2.7 and 3.6 on mac and linux. 

I'll continue to upload wheels for mac and linux each time we have a new release.

I believe this now meets the original ask of the issue - a way to easily/quickly install arctic, which wheels now provide. I'm going to close this, but feel free to open again if you have a useful use case for having an arctic docker image. Also feel free to re-open @jamesblackburn if you think this is something we'd ever do/support/want.

**Comment by davidwneary** [comment]
@bmoscon - Thanks a lot for the quick response!
