### ISSUE TITLE
cannot get data with data_range specified in version store

### ISSUE THREAD

**Issue by gaussleescorpio** [manahl/arctic#507]
#### Arctic Version
1.61
```
# Arctic version here
```

#### Arctic Store

```
VersionStore,
```

#### Platform and version

Ubuntu 16.04

#### Description of problem and/or code sample that reproduces the issue

I get a dataframe df which looks like below:

![image](https://user-images.githubusercontent.com/17249981/36420946-a81a03a0-1671-11e8-81fd-acefbf1464a3.png)

`store = Arctic("localhost")
store.list_libraries()
store.initialize_library('gausstest', lib_type=arctic.VERSION_STORE)
library = store['gausstest']
library.write('DSHBTC', df1)`

The above code has no problem to execute. However, when I read data with data_range, the function gives me empty dataframe.

`library.read('DSHBTC', date_range=arctic.date.DateRange("2018-02-03", "2018-02-06")).data`

I wonder why? Is it because arctic can only recognize datatime with resolution to date instead of hours, minutes and seconds?

**Comment by bmoscon** [comment]
if you provide the code you used to write the data I can probably tell you what you are doing wrong. Its possible the index is not being correctly created in your dataframe. (i.e if thats a string or object rather than a DateTimeIndex)

**Comment by bmoscon** [comment]
never heard back - the code specified is not sufficient - i.e. your screen shot shows dates from 2018-02-18 to 2018-02-19, but your DateRange is from 2018-02-03 to 02-06, so I have no way of knowing if you actually have data there or not since you never provided the data. Closing this - if you still have an issue and want us to look into it we'll need more information.
