### ISSUE TITLE
Issue with users creation

### ISSUE THREAD

**Issue by rtadewald** [manahl/arctic#601]
#### Arctic Version

```
# 1.67.1
```

#### Arctic Store

```
#All of them
```

#### Platform and version

Ubuntu 18.04 LTS

#### Description of problem and/or code sample that reproduces the issue

I'm having some trouble with autentication/roles on MongoDB/Arctic.
I've created a cluster of databases on Google Cloud Engine using [Cloud Lancher](https://console.cloud.google.com/marketplace/details/click-to-deploy-images/mongodb). 

After that, I've setup authentication to True in **sudo vim /etc/mongod.conf** and logged in and create a 
root user using `db.createUser( {user: "user", pwd: "pass", roles:["root"] })`. But when I try to use Arctic, strange things starts happening:

```
from arctic import Arctic
store = Arctic(mongo_host='mongodb://user:pass@remote_ip:27017/admin')
store.list_libraries()
```
**out:** []

`store.initialize_library('RISK.TRADES')`
**out:** <class 'pymongo.errors.NotMasterError'> set_library_metadata [not master], retrying 3

My sorry, I know that's a basic question, but's not very clear to me how can I handle authentication in Arctic. My goal is to create some superuser that has the hability to use `initialize_library()` and `delete_library()` commands and other users just can call `read()` on libraries, but I could now understand how can I do that using **arctic.auth** or [something like this](https://github.com/manahl/arctic/issues/563). 

Thanks for you support and for this amazing library.

**Comment by dimosped** [comment]
Hello,
the init mongo host str you use should work for obtaining an authenticated connection for user, and use it in your Arctic instance.

The error you see is because you hit a non-primary mongod directly. Try using the IP of the primary instead, or better hit the mongos IP if you have one.

Regarding the auth question, you could register custom auth hooks:
https://github.com/manahl/arctic/blob/master/tests/integration/test_arctic_multithreading.py#L51

E.g. you could have a method which obtains the user credentials and registers itself:
https://github.com/manahl/arctic/blob/master/arctic/hooks.py#L35

Then, when a new Arctic instance is created or connection is reset, you'll authenticate using custom user/passwd.
https://github.com/manahl/arctic/blob/master/arctic/arctic.py#L136

At the mongo side, you can have a user with admin rights, and one with read-only rights:
https://docs.mongodb.com/manual/tutorial/enable-authentication/
https://docs.mongodb.com/manual/reference/built-in-roles/#read

**Comment by rtadewald** [comment]
I've managed this problem with the autenticantion and roles in MongoDB.
Thank you very much.
