### ISSUE TITLE
write to TickStore, maximum 100000 items

### ISSUE THREAD

**Issue by eduedix** [manahl/arctic#607]
#### Arctic Version

```
1.68.0
```

#### Arctic Store

```
TickStore
```

#### Description of problem and/or code sample that reproduces the issue

https://gist.github.com/eduedix/6ea4381f424a5b9de45faf939ed66574

As seen in the code above, the written and read  `df`s do not match. I have also tried to `write`ing `df.sort_index()`. There was no difference in the results besides that it eliminated `sorting!` warning.

The read df has `100000` items.

**Comment by eduedix** [comment]
turns out I was hitting `chunk_size`.

**Comment by eduedix** [comment]
Sure, though let's assume I will store ticks with intervals but need to initialize the db with 1y worth of data. In this case, should I divide and store with intervals again? :)

**Comment by bmoscon** [comment]
In that case I'd recommend version store or chunkstore. tickstore is designed for realtime, incoming, continuously ticking data, not backfilling historical data. If you want to use tickstore, just divide the data into reasonably sized chunks, maybe `5D`, `W` (can't really say since I'm not sure what the data is)
